FROM python:3.7

# COLOCA TODOS OS ARQUIVOS DO DIRETORIO BUILD NO DIRETORIO /APP
COPY . /app

# SETA O DIRETORIO /APP COMO PADRAO
WORKDIR /app

# INSTALA OS REQUISITOS
RUN pip install -r requirements.txt

# RODA O MODULO PRINCIPAL
CMD [ "python", "./main.py" ]

# ESPECIFICA A PORTA PARA DEPURAR A APLICACAO DE FORMA REMOTA
EXPOSE 5678